name: Build & Push Docker Release Image
description: |
  Builds release image of a project and pushes to cloud
  ****
  envInputs:
    GITHUB_TOKEN: GitHub token. Is used to checkout `davinci` branch
    GCR_ACCOUNT_KEY: Necessary token to push image to Google cloud

inputs:
  sha:
    required: true
    description: Commit hash that will be used as a tag for the Docker image
  repository-name:
    required: true
    description: Name of repository. It's used to determine an image name
  environment:
    required: false
    default: staging
    description: Used to determine additional procedures while creating a Docker image || enum<<br/>`temploy`,<br/>`staging`,<br/>`production`,<br/>>
  dist-folder:
    required: false
    default: ./dist
    description: Path to the folder with the built project
  scope:
    required: false
    default: ''
    description: Used to determine the scope of the built project. Usefull in multihost monorepo projects to build only one project.

runs:
  using: composite
  steps:
    - uses: toptal/davinci-github-actions/yarn-install@v6.0.0

    # Use yarn lerna run build --scope=${{ inputs.scope}} if the scope is set, otherwise use yarn build
    - name: Build
      shell: bash
      run: |
        if [[ -z "${{ inputs.scope }}" ]]; then
          yarn build
        else
          yarn lerna run build --scope=${{ inputs.scope}}
        fi



    - uses: toptal/davinci-github-actions/build-push-image@v6.0.0
      with:
        sha: ${{ inputs.sha }}
        image-name: ${{ inputs.repository-name }}-release
        environment: ${{ inputs.environment }}
        docker-file: ./davinci/packages/ci/src/configs/docker/Dockerfile.gha-deploy
        build-args: |
          ENV_RUNTIME_ENTRYPOINT=./davinci/packages/ci/src/configs/docker/env-runtime.entrypoint.sh
          DIST_FOLDER=${{ inputs.dist-folder }}
          NGINX_CONFIG=./davinci/packages/davinci/docker/nginx-vhost.conf
          VERSION=${{ inputs.sha }}
