name: Extract Env variables
description: Extract and Export ENV variables from env file
outputs:
  variables:
    description: 'Comma separated list of env variables with `ENV.` prefix'
    value: ${{ steps.env-variables.outputs.result }}
inputs:
  github-token:
    required: true
    description: 'GITHUB Token'
  filename:
    required: false
    description: '`.env` file name from which to read variables, e.g.: `.env.temploy`'
    default: .env

runs:
  using: composite
  steps:
    - name: Extract Env variables
      id: env-variables
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          const fs = require('fs')
          const qs = require('querystring')

          if (!fs.existsSync('${{ inputs.filename }}')) return ''

          return fs
            .readFileSync('${{ inputs.filename }}')
            .toString()
            .split(/\n/)
            .filter(line => !line.startsWith('#') && line.length > 0)
            .map(line => `ENV.${line},davinci-app.ENV.${line}`)
            .join(',')
