name: Automatically merge release pull request
description: |
  Automatically merges Version Packages pull requests to the main branch (for all types of releases – patch, minor, major).

inputs:
  token:
    required: true
    description: GitHub token to create a comment and merge pull request
  pr-number:
    required: true
    description: Pull request number

runs:
  using: composite
  steps:
    - name: Merge pull request
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        pr-number: 
        script: |
          const repository = context.repo
          const commentBody = "This pull request will be merged automatically"

          await github.rest.issues.createComment({
            owner: repository.owner,
            issue_number: ${{ inputs.pr-number }},
            repo: repository.repo,
            body: commentBody,
          })

          await github.rest.pulls.merge({
            merge_method: "squash",
            owner: repository.owner,
            pull_number: ${{ inputs.pr-number }},
            repo: repository.repo,
          })
