name: Print coverage report in a PR
description: |
  Merge all report files in `path` folder using `nyc merge`
  Then prints coverage report as a comment in related PR

inputs:
  path:
    description: Path to a folder with code coverage file(s)
    required: false
    default: code-coverage
  reporter:
    description: 'Istanbul reporter for coverage output - see https://istanbul.js.org/docs/advanced/alternative-reporters/'
    required: false
    default: text-summary
  github-token:
    description: GitHub token
    required: false

runs:
  using: composite
  steps:
    - name: Merge coverage files
      shell: bash
      run: |
        mkdir merged-coverage
        npx nyc merge ${{ inputs.path }} merged-coverage/coverage.json

    - name: Print Coverage
      uses: tj-actions/coverage-reporter@3eef0fe5e5d3881cc8faa2fb1365296edbf8af60
      with:
        coverage-command: npx nyc report --reporter ${{ inputs.reporter }} --temp-dir merged-coverage
        token: ${{ inputs.token || github.token }}

