name: PR Conventional to Toptal Commit
description: Convert a PR title from conventional commits to Toptal commit

inputs:
  github-token:
    required: true
    description: GitHub user token

runs:
  using: composite
  steps:
    - name: Rename pull request
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const capitalize = (str) => (str[0] ?? '').toUpperCase() + str.slice(1)
          const convertConventional = (title) => {
            const pattern = /^\w+(?:\(.+\))?: (.*)$/
            const [, titleMessage = ''] = title.match(pattern) ?? []

            return capitalize(titleMessage.trim()) ?? title
          }

          const newPr = {
            owner: 'toptal',
            repo: 'davinci',
            pull_number: 2231,
            title: convertConventional('chore(deps): update a package')
          }

          github.rest.pulls.update(newPr)
