name: 'Report affected packages'
description: 'Generate a diagram of affected monorepo packages as a job summary. Works with workflows triggered by pull_request event.'

inputs:
  node-version:
    required: false
    default: 20
    description: 'Node.js version used. The action is guaranteed to work only with Node.js@20 (default value)'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - uses: masesgroup/retrieve-changed-files@2e42889ff54e0810cf088f73a38a2db5a9d0684f
      id: files
      with:
        format: 'json'

    - shell: bash
      run: |
        echo '${{ steps.files.outputs.all }}' >> changed_files.json

    - name: Get workspace info
      shell: bash
      run: yarn --silent --no-default-rc workspaces info > info.json

    - name: Run script to check Owners Approvals
      run: node ${{ github.action_path }}/diagram.js >> $GITHUB_STEP_SUMMARY
      shell: bash
      env:
        CHANGED_FILES_PATH: changed_files.json
        INFO_PATH: info.json
