name: Build & Push Storybook Docker Image

description: |
  Builds a release image of Storybook and pushes it to the cloud.
  ****
  envInputs:
    GITHUB_TOKEN: GitHub token. Is used to checkout `davinci` branch
    GCR_ACCOUNT_KEY: Necessary token to push image to Google cloud

inputs:
  sha:
    description: Commit hash that will be used as a tag for the Docker image
    required: true
  davinci-branch:
    description: Custom davinci branch
    required: false
    default: master
  dist-folder:
    description: Path to folder where Storybook is built
    required: false
    default: ./storybook-static
  build-command:
    description: Command to build Storybook with
    required: false
    default: storybook:build

runs:
  using: composite
  steps:
    - name: Build Storybook
      shell: bash
      env:
        BUILD_COMMAND: ${{ inputs.build-command }}
      run: yarn "$BUILD_COMMAND"

    - name: Specify repository name
      id: get-repo
      shell: bash
      run: echo ::set-output name=repository_name::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")

    - name: Build and Push Storybook Image
      uses: toptal/davinci-github-actions/build-push-image@v3.1.0
      with:
        sha: ${{ inputs.sha }}
        image-name: ${{ steps.get-repo.outputs.repository_name }}-storybook-release
        build-args: |
          DIST_FOLDER=${{ inputs.dist-folder }}
          NGINX_CONFIG=./davinci/packages/davinci/docker/nginx-vhost-storybook.conf
          VERSION=${{ inputs.sha }}
        docker-file: ./davinci/packages/ci/src/configs/docker/Dockerfile.storybook
        davinci-branch: ${{ inputs.davinci-branch }}


