name: Notify JIRA About External Contribution

description: Notifies JIRA about external contribution

inputs:
  team:
    required: true
    description: Team that we are checking against
  repo:
    required: true
    description: Repository name
  pull-number:
    required: true
    description: Nth pull request
  jira-hook:
    required: true
    description: JIRA automation hook for contribution
  github-token:
    required: true
    description: Token for authorization

runs:
  using: composite
  steps:
    - name: Get PR data
      id: get-pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{org}/{repo}/pulls/{pull-number}
        org: toptal
        repo: ${{ inputs.repo }}
        pull-number: ${{ inputs.pull-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - uses: toptal/davinci-github-actions/is-team-member@v4.4.2
      id: is-team-member
      with:
        team: ${{ inputs.team }}
        login: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        github-token: ${{ inputs.github-token }}

    - name: Define if PR is eligible - PR authored by external contributor and is not draft
      env:
        IS_NOT_DEPENDABOT_BOT: ${{ fromJson(steps.get-pr.outputs.data).user.login != 'dependabot[bot]' }}
      id: is-pr-eligible
      shell: bash
      run: |
        echo "::set-output name=result::${{ fromJson(steps.is-team-member.outputs.result) == false && fromJson(steps.get-pr.outputs.data).draft == false && env.IS_NOT_DEPENDABOT_BOT }}"

    - name: Jira issue can be created
      id: jira-issue-can-be-created
      shell: bash
      run: |
        echo "::set-output name=result::${{ fromJson(steps.is-pr-eligible.outputs.result) == true && !contains(github.event.pull_request.labels.*.name, 'contribution') }}"

    - name: Add label - JIRA issue created - for non-Draft PR
      if: ${{ fromJson(steps.is-pr-eligible.outputs.result) == true }}
      uses: andymckay/labeler@1.0.4
      with:
        add-labels: "contribution"

    - name: Notify JIRA
      if: ${{ fromJson(steps.is-pr-eligible.outputs.result) == true && fromJson(steps.jira-issue-can-be-created.outputs.result) == true }}
      shell: bash
      env:
        JIRA_HOOK: ${{ inputs.jira-hook }}
        REPO: ${{ inputs.repo }}
        TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
        AUTHOR: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        AUTHOR_URL: ${{ fromJson(steps.get-pr.outputs.data).user.html_url }}
        NUMBER: ${{ fromJson(steps.get-pr.outputs.data).number }}
        URL: ${{ fromJson(steps.get-pr.outputs.data).html_url }}
      run: bash ${{ github.action_path }}/notify-jira.sh

    - name: Greet author
      if: ${{ fromJson(steps.is-pr-eligible.outputs.result) == true && fromJson(steps.jira-issue-can-be-created.outputs.result) == true }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ fromJson(steps.get-pr.outputs.data).number }},
            owner: "toptal",
            repo: "${{ inputs.repo }}",
            body:
            `
            Greetings from FX team, @${{ fromJson(steps.get-pr.outputs.data).user.login }} :wave:\r\n\r\n
            Thank you so much for contributing :bow:\r\n\r\n
            We have got **high priority ticket** generated on [our Kanban board](https://toptal-core.atlassian.net/jira/software/c/projects/FX/boards/491) so we will do our best to make your experience supreme!\r\n\r\n
            What's next? We will collaborate using [this workflow](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/2396094469/Handling+contribution). For you this practically means making sure [DONE criteria](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/1933377584/Done+criteria) is met and responding promptly to code review comments :wink:\r\n\r\n
            :pray: please, help us improve, [rate your contributing experience](https://forms.gle/unzJBEJAHRz7LEtX8) after merge
            `
          })
