name: Notify JIRA About External Contribution

description: Notifies JIRA about external contribution

inputs:
  team:
    required: true
    description: Team that we are checking against
  repo:
    required: true
    description: Repository name
  pull-number:
    required: true
    description: Nth pull request
  jira-hook:
    required: true
    description: JIRA automation hook for contribution
  github-token:
    required: true
    description: Token for authorization
  notify-about-major-dependabot-updates:
    required: false
    description: Notify about major dependabot updates
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Get PR data
      id: get-pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{org}/{repo}/pulls/{pull-number}
        org: toptal
        repo: ${{ inputs.repo }}
        pull-number: ${{ inputs.pull-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Check if author is a member of specific team
      uses: toptal/davinci-github-actions/is-team-member@v6.0.0
      id: is-team-member
      with:
        team: ${{ inputs.team }}
        login: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        github-token: ${{ inputs.github-token }}

    - name: Check if PR comes fron dependabot
      env:
        IS_DEPENDABOT: ${{ fromJson(steps.get-pr.outputs.data).user.login == 'dependabot[bot]' }}
      id: is-dependabot
      shell: bash
      run: |
        echo "result=${{ env.IS_DEPENDABOT }}" >> $GITHUB_OUTPUT

    - name: Check if Jira issue already exists
      id: jira-issue-already-exists
      shell: bash
      run: |
        echo "result=${{ contains(github.event.pull_request.labels.*.name, 'contribution') }}" >> $GITHUB_OUTPUT

    - name: Decide if Jira ticket should be created
      id: create-jira-issue
      env:
        IS_TEAM_MEMBER: ${{ fromJson(steps.is-team-member.outputs.result) }}
        IS_DEPENDABOT: ${{ steps.is-dependabot.outputs.result }}
        IS_DRAFT: ${{ fromJson(steps.get-pr.outputs.data).draft }}
        NOTIFY_ABOUT_MAJOR_DEPENDABOT_UPDATES: ${{ inputs.notify-about-major-dependabot-updates }}
        JIRA_ISSUE_ALREADY_EXISTS: ${{ steps.jira-issue-already-exists.outputs.result }}
        PR_TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
      shell: bash
      run: |
        echo "Checking if Jira ticket already exists or PR is a draft"
        jiraIssueAlreadyExists=${{ env.JIRA_ISSUE_ALREADY_EXISTS }}
        isDraft=${{ env.IS_DRAFT }}
        if [[ jiraIssueAlreadyExists == "true" || isDraft == "true" ]]
        then
          echo "Jira ticket already exists or PR is a draft, exiting"
          echo "result=false" >> $GITHUB_OUTPUT
          exit
        fi

        # Define function to extract major versions from PR title
        old_major=""
        new_major=""
        extractMajorVersions() {
          echo "Checking if PR is a major update, PR title: $pr_title"

          # Assign function parameter to a variable
          pr_title=$1

          # Extract number version using grep utility
          #   - "--only-matching" prints only the matched (non-empty) parts of a matching line
          #   - "--extended-regexp" allows to use extended regular expressions
          #   - "cut -d' ' -f2" extracts the second word from the matched line
          #   - "cut -d'.' -f1" extracts the first part of the version number
          old_major_value=$(echo "$pr_title" | grep --only-matching --extended-regexp 'from [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)

          # Check if the variable is empty
          if [ -z "$old_major_value" ]; then
              echo "Error: Unable to extract old major version." >&2
          else
              echo "Old major: $old_major_value"
              old_major=$old_major_value
          fi

          # Extracting the new major version using grep
          new_major_value=$(echo "$pr_title" | grep --only-matching --extended-regexp 'to [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
          
          # Check if the variable is empty
          if [ -z "$new_major_value" ]; then
              echo "Error: Unable to extract new major version." >&2
          else
              echo "New major: $new_major_value"
              new_major=$new_major_value
          fi
        }

        isDependabot=${{ env.IS_DEPENDABOT }}
        isMajorUpdate=false
        # TODO: REVERT IT TO TRUE
        if [[ $isDependabot == "false" ]]
        then
          echo "It is dependabot PR"
          pr_title="${{ env.PR_TITLE }}"
          extractMajorVersions "$pr_title"

          if [ "$old_major" != "$new_major" ]; then
            isMajorUpdate=true
          fi

          echo "Major update: $isMajorUpdate"
        fi

        isTeamMember=${{ env.IS_TEAM_MEMBER }}
        notifyAboutMajorDependabotUpdates=${{ env.NOTIFY_ABOUT_MAJOR_DEPENDABOT_UPDATES }}
        if [[ $notifyAboutMajorDependabotUpdates == "true" && $isDependabot == "true" ]]; then
          if [[ $isMajorUpdate == "true" ]]; then
            echo "Major dependabot update, exiting"
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "Non-major dependabot update"
            echo "result=false" >> $GITHUB_OUTPUT
          fi

          exit
        fi

        if [[ $isTeamMember == "false" ]]; then
          echo "Author is not a member of the team, exiting"
          echo "result=true" >> $GITHUB_OUTPUT
          exit
        fi

        echo "result=false" >> $GITHUB_OUTPUT

    # Create JIRA issue
    - name: Add label - JIRA issue created - for non-Draft PR
      if: ${{ fromJson(steps.create-jira-issue.outputs.result) == true }}
      uses: andymckay/labeler@1.0.4
      with:
        repo-token: ${{ inputs.github-token }}
        add-labels: "contribution"

    - name: Create JIRA ticket
      if: ${{ fromJson(steps.create-jira-issue.outputs.result) == true }}
      shell: bash
      env:
        JIRA_HOOK: ${{ inputs.jira-hook }}
        REPO: ${{ inputs.repo }}
        TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
        AUTHOR: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        AUTHOR_URL: ${{ fromJson(steps.get-pr.outputs.data).user.html_url }}
        NUMBER: ${{ fromJson(steps.get-pr.outputs.data).number }}
        URL: ${{ fromJson(steps.get-pr.outputs.data).html_url }}
      run: bash ${{ github.action_path }}/notify-jira.sh

    - name: Greet author
      if: ${{ fromJson(steps.create-jira-issue.outputs.result) == true && fromJson(steps.is-dependabot.outputs.result) == false }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ fromJson(steps.get-pr.outputs.data).number }},
            owner: "toptal",
            repo: "${{ inputs.repo }}",
            body:
            `
            Greetings from FX team, @${{ fromJson(steps.get-pr.outputs.data).user.login }} :wave:\r\n\r\n
            Thank you so much for contributing :bow:\r\n\r\n
            We have got **high priority ticket** generated on [our Kanban board](https://toptal-core.atlassian.net/jira/software/c/projects/FX/boards/491) so we will do our best to make your experience supreme!\r\n\r\n
            What's next? We will collaborate using [this workflow](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/2396094469/Handling+contribution). For you this practically means making sure [DONE criteria](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/1933377584/Done+criteria) is met and responding promptly to code review comments :wink:\r\n\r\n
            :pray: please, help us improve, [rate your contributing experience](https://forms.gle/unzJBEJAHRz7LEtX8) after merge
            `
          })
