name: Notify JIRA About External Contribution

description: Notifies JIRA about external contribution

inputs:
  team:
    required: true
    description: Team that we are checking against
  repo:
    required: true
    description: Repository name
  pull-number:
    required: true
    description: Nth pull request
  jira-hook:
    required: true
    description: JIRA automation hook for contribution
  github-token:
    required: true
    description: Token for authorization
  should-notify-about-major-dependency-updates:
    required: false
    description: Specifies if action should create Jira issues for major dependency updates (authored by dependabot, minor and patch versions are ignored)
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Get PR data
      id: get-pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{org}/{repo}/pulls/{pull-number}
        org: toptal
        repo: ${{ inputs.repo }}
        pull-number: ${{ inputs.pull-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Check if author is a member of specific team
      uses: toptal/davinci-github-actions/is-team-member@v6.0.0
      id: is-team-member
      with:
        team: ${{ inputs.team }}
        login: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        github-token: ${{ inputs.github-token }}

    - name: Check if PR comes fron dependabot
      env:
        IS_DEPENDABOT_PULL_REQUEST: ${{ fromJson(steps.get-pr.outputs.data).user.login == 'dependabot[bot]' }}
      id: is-dependabot-pull-request
      shell: bash
      run: |
        echo "result=${{ env.IS_DEPENDABOT_PULL_REQUEST }}" >> $GITHUB_OUTPUT

    - name: Check if Jira issue already exists
      id: jira-issue-already-exists
      shell: bash
      run: |
        echo "result=${{ contains(github.event.pull_request.labels.*.name, 'contribution') }}" >> $GITHUB_OUTPUT

    - name: Decide if Jira issue should be created
      id: should-create-jira-issue
      env:
        IS_TEAM_MEMBER: ${{ fromJson(steps.is-team-member.outputs.result) }}
        IS_DEPENDABOT_PULL_REQUEST: ${{ steps.is-dependabot-pull-request.outputs.result }}
        IS_DRAFT: ${{ fromJson(steps.get-pr.outputs.data).draft }}
        SHOULD_NOTIFY_ABOUT_MAJOR_DEPENDENCY_UPDATES: ${{ inputs.should-notify-about-major-dependency-updates }}
        JIRA_ISSUE_ALREADY_EXISTS: ${{ steps.jira-issue-already-exists.outputs.result }}
        PR_TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
      shell: bash
      run: bash ${{ github.action_path }}/should-create-jira-issue.sh

    - name: Add contribution label to pull request
      if: ${{ fromJson(steps.should-create-jira-issue.outputs.result) == true }}
      uses: andymckay/labeler@1.0.4
      with:
        repo-token: ${{ inputs.github-token }}
        add-labels: "contribution"

    - name: Create JIRA issue
      if: ${{ fromJson(steps.should-create-jira-issue.outputs.result) == true }}
      shell: bash
      env:
        JIRA_HOOK: ${{ inputs.jira-hook }}
        REPO: ${{ inputs.repo }}
        TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
        AUTHOR: ${{ fromJson(steps.get-pr.outputs.data).user.login }}
        AUTHOR_URL: ${{ fromJson(steps.get-pr.outputs.data).user.html_url }}
        NUMBER: ${{ fromJson(steps.get-pr.outputs.data).number }}
        URL: ${{ fromJson(steps.get-pr.outputs.data).html_url }}
      run: bash ${{ github.action_path }}/notify-jira.sh

    - name: Greet author
      if: ${{ fromJson(steps.should-create-jira-issue.outputs.result) == true && fromJson(steps.is-dependabot-pull-request.outputs.result) == false }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ fromJson(steps.get-pr.outputs.data).number }},
            owner: "toptal",
            repo: "${{ inputs.repo }}",
            body:
            `
            Greetings from FX team, @${{ fromJson(steps.get-pr.outputs.data).user.login }} :wave:\r\n\r\n
            Thank you so much for contributing :bow:\r\n\r\n
            We have got **high priority ticket** generated on [our Kanban board](https://toptal-core.atlassian.net/jira/software/c/projects/FX/boards/491) so we will do our best to make your experience supreme!\r\n\r\n
            What's next? We will collaborate using [this workflow](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/2396094469/Handling+contribution). For you this practically means making sure [DONE criteria](https://toptal-core.atlassian.net/wiki/spaces/FE/pages/1933377584/Done+criteria) is met and responding promptly to code review comments :wink:\r\n\r\n
            :pray: please, help us improve, [rate your contributing experience](https://forms.gle/unzJBEJAHRz7LEtX8) after merge
            `
          })
