name: 'Access Secrets from GSM'
description: 'Access secrets from Google Secret Manager using WIF to authenticate to Google Cloud'
inputs:
  # The name of the project where the secret is stored
  workload_identity_provider:
    description: 'The name of the project where the secret is stored'
    required: true
  # The name of the service account to use to access the secret
  service_account:
    description: 'The name of the service account to use to access the secret'
    required: true
  # The name of the secret to retrieve
  secrets_name:
    description: 'The name of the secrets to retrieve'
    required: true
outputs:
  secrets:
    description: 'The secrets retrieved from GSM in JSON format'
    value: ${{ toJson(steps.get-secrets.outputs) }}
runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud using WIF
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Get the secrets from GSM
      id: get-secrets
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: ${{ inputs.secrets_name }}

    - name: Remove gha-cred file content
      shell: bash
      run: |-
        echo -n "" > "${GOOGLE_GHA_CREDS_PATH}"

    - name: unset GOOGLE_APPLICATION_CREDENTIALS
      shell: bash
      run: |-
        echo "GOOGLE_APPLICATION_CREDENTIALS=" >> $GITHUB_ENV
