name: Upload Source Maps to Sentry
description: |
  It creates a new Sentry release and uploads source maps
  ****
  envInputs:
    SENTRY_AUTH_TOKEN: Sentry token. Is used to upload source files to Sentry

inputs:
  sentry-project:
    required: true
    description: The name of the Sentry project to upload source files to
  working-directory:
    required: false
    description: Specifies the working directory where the command is run
    default: '.'
  url-prefix:
    required: false
    description: Sets URL prefix for files
  app-build-directory:
    required: false
    description: Directory of the built application
  release-name:
    required: false
    description: Name for the uploaded source maps

runs:
  using: composite
  steps:
    - name: Upload source maps to Sentry
      env:
        SENTRY_ORG: toptal
        SENTRY_PROJECT: ${{ inputs.sentry-project }}
        URL_PREFIX: ${{ inputs.url-prefix }}
        APP_BUILD_DIRECTORY: ${{ inputs.app-build-directory }}
        RELEASE_NAME: ${{ inputs.release-name }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ -z "$SENTRY_AUTH_TOKEN" ]]
        then
          echo >&2 "You don't have SENTRY_AUTH_TOKEN set up in your GH Action."
          exit 1
        fi

        if [[ $(yarn davinci-engine help) == *"sentry-upload-source-maps"* ]]
        then
          yarn davinci-engine sentry-upload-source-maps \
            ${URL_PREFIX:+"--url-prefix=$URL_PREFIX"} \
            ${APP_BUILD_DIRECTORY:+"--app-build-directory=$APP_BUILD_DIRECTORY"} \
            ${RELEASE_NAME:+"--release-name=$RELEASE_NAME"}
        else
          echo "Your current @toptal/davinci-engine version does not support uploading source maps to Sentry. Please update @toptal/davinci-engine package version in your app."
        fi
