name: Generate GQL Types
description: Generate graphql types before application build

inputs:
  generate-types-command:
    description: Command to generate gql types
    default: generate:types
  workload_identity_provider:
    description: 'The Google Cloud Workload Identity Provider. E.g. projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
    required: true
  service_account:
    description: 'The Google Cloud Service Account email. E.g. my-service-account@my-project.iam.gserviceaccount.com'
    required: true

runs:
  using: composite
  steps:
    - name: Auth Google cloud toolchain
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Setup Google cloud toolchain
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Check types cache
      uses: actions/cache@v4
      id: gql-types-cache
      with:
        path: |
          libs/graphql
          **/*.types.tsx
        key: ${{ runner.os }}-types-${{ hashFiles('yarn.lock', '**/codegen.js', '**/*.graphql', '**/*.graphql.ts', '**/*.gql.ts') }}

    - name: Generate types
      if: ${{ steps.gql-types-cache.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        COMMAND: ${{ inputs.generate-types-command }}
      run: yarn $COMMAND
