name: Install dependencies
description: Install and cache node modules with yarn
inputs:
  npm-token:
    description: Access token type **Read-only**. Required for repository with private dependencies. If undefined, `env.NPM_TOKEN` is used
    required: false
  cache-version:
    description: "Cache version"
    default: "0.0"
    required: false
  path:
    description: Relative path under $GITHUB_WORKSPACE where to run `yarn install` command
    default: .
    required: false
  checkout-token:
    description: Repository checkout access token `GITHUB_TOKEN`. Required for self-hosted runners
    required: false
  npm-gar-token:
    description: Repository npm Artifact Registry access token `NPM_GAR_TOKEN`. Required when using self-hosted runners with npm in GAR (Google Artifact Registry, the npm registry works as a proxy-cache, downloading and storing the public npm packages)
    required: false
  max-attempts:
    description: How many times to retry installing. This is specially useful if the building of packages might fail because of network connections
    default: "1"
    required: false
outputs:
  cache-hit:
    description: "Indicates an exact match was found for `node_modules` || boolean"
    value: ${{ steps.node-modules-cache.outputs.cache-hit || steps.node-modules-cache-custom.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Set node version
      id: set-node-version
      run: echo version=$(node -v) >> $GITHUB_OUTPUT
      shell: bash

    - name: Get yarn cache
      id: yarn-cache
      run: echo dir=$(yarn cache dir) >> $GITHUB_OUTPUT
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token || env.NPM_TOKEN }}

    - name: Detect caching strategy
      id: caching-strategy
      shell: bash
      run: |
        echo "Check if we can cache deps on Toptal's infrastructure by using toptal/actions/cache"
        echo "use_toptal_cache=${{inputs.checkout-token && inputs.npm-gar-token && (contains(runner.name, 'inf-gha-runners') || contains(runner.name, 'ubuntu2204'))}}" >> $GITHUB_OUTPUT


    # This step is needed only because we want to update the cache when a new workspace
    # package has been added and we want symlinks to be presented in ./node_modules folder
    - name: Generate workspaces info
      working-directory: ${{ inputs.path }}
      run: |
        if grep -q "\"workspaces\":" package.json; then
          yarn --no-default-rc workspaces --json info > tmp-workspaces.json
        fi
      shell: bash

    - name: Checkout `cache action` from actions repository
      if: steps.caching-strategy.outputs.use_toptal_cache == 'true'
      uses: actions/checkout@v4
      with:
        repository: toptal/actions
        # TODO: reset to specific version
        ref: explicit-auth-for-cache-action
        token: ${{ inputs.checkout-token }}
        path: ./.github/cache_action/

    - name: Decode Service Account JSON
      id: decode-sa
      if: steps.caching-strategy.outputs.use_toptal_cache == 'true'
      run: |
        DECODED_JSON=$(echo "${{ inputs.npm-gar-token }}" | base64 -d | tr -d '\n' | base64 -d)
        EOF=$(openssl rand -base64 12 | tr -d '\n') # Unique delimiter
        echo "credentials_json<<$EOF" >> $GITHUB_OUTPUT
        echo "$DECODED_JSON" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache yarn and node_modules folder
      if: steps.caching-strategy.outputs.use_toptal_cache == 'true'
      uses: ./.github/cache_action/cache/
      id: node-modules-cache-custom
      with:
        # Do not change the order of the values because if something goes wrong with the network or node_modules during
        # the caching process, GitHub can still end up creating a valid cache entry.
        # The cache from yarn is smaller and of higher priority for us
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles(format('{0}/yarn.lock', inputs.path), format('{0}/tmp-workspaces.json', inputs.path)) }}-${{ inputs.cache-version }}
        credentials-json: ${{ steps.decode-sa.outputs.credentials_json }}

    - name: Cache yarn and node_modules folder
      if: steps.caching-strategy.outputs.use_toptal_cache != 'true'
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        # Do not change the order of the values because if something goes wrong with the network or node_modules during
        # the caching process, GitHub can still end up creating a valid cache entry.
        # The cache from yarn is smaller and of higher priority for us
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles(format('{0}/yarn.lock', inputs.path), format('{0}/tmp-workspaces.json', inputs.path)) }}-${{ inputs.cache-version }}

    - name: Delete temporary tmp-workspaces.json
      shell: bash
      run: |
        [ -e tmp-workspaces.json ] && rm tmp-workspaces.json || echo "OK"

    # This step creates .npmrc file that references to npm registry in GAR (Google Artifact Registry)
    # The npm registry works as a proxy-cache, downloading and storing the public npm packages
    - name: Create .npmrc file using npm Artifact Registry
      if: steps.caching-strategy.outputs.use_toptal_cache == 'true'
      run: |
        if [ -f ${{ inputs.path }}/.npmrc ]; then
          mv ${{ inputs.path }}/.npmrc ${{ inputs.path }}/.npmrc.original
        fi

        echo "registry=https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/" > ${{ inputs.path }}/.npmrc &&
        echo "//us-central1-npm.pkg.dev/toptal-ci/npm-registry/:username=_json_key_base64" >> ${{ inputs.path }}/.npmrc &&
        echo "//us-central1-npm.pkg.dev/toptal-ci/npm-registry/:_password=${{ inputs.npm-gar-token }}" >> ${{ inputs.path }}/.npmrc &&

        echo "@toptal:registry=https://registry.npmjs.org/" >> ${{ inputs.path }}/.npmrc &&
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token || env.NPM_TOKEN }}" >> ${{ inputs.path }}/.npmrc &&

        echo "@topkit:registry=https://registry.npmjs.org/" >> ${{ inputs.path }}/.npmrc &&
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token || env.NPM_TOKEN }}" >> ${{ inputs.path }}/.npmrc &&
        echo "always-auth=true" >> ${{ inputs.path }}/.npmrc
      shell: bash

    # This step changes the public npm registry in yarn.lock file to npm in AR
    # We still use the public npm registry to our private packages
    - name: Change registry in yarn.lock file to npm Artifact Registry
      if: steps.caching-strategy.outputs.use_toptal_cache == 'true'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        echo "Snapshot original yarn.lock file to restore it later"
        cp yarn.lock yarn.lock.original

        PUBLIC_YARN_REGISTRY="https://registry.yarnpkg.com/"
        PUBLIC_NPM_REGISTRY="https://registry.npmjs.org/"
        TOPTAL_NPM_REGISTRY="https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/"

        echo "Updating registry URLs in yarn.lock file and writing output to yarn.lock.temp"
        # NOTE: setting IFS= (empty) for `read -r line` ensures that:
        #  1. Leading and trailing whitespace in each line is preserved
        #  2. The line is read exactly as-is, without any field splitting
        #  3. Any whitespace characters within the line remain untouched
        while IFS= read -r line; do
            if [[ $line =~ /@toptal|/@topkit ]]; then
                # For @toptal and @topkit packages, keep the original registry
                echo "$line" >> yarn.lock.temp
            else
                # For all other packages, replace with new registry
                modified_line="${line//$PUBLIC_YARN_REGISTRY/$TOPTAL_NPM_REGISTRY}"
                modified_line="${modified_line//$PUBLIC_NPM_REGISTRY/$TOPTAL_NPM_REGISTRY}"
                echo "$modified_line" >> yarn.lock.temp
            fi
        done < yarn.lock

        echo "Replacing yarn.lock file with yarn.lock.temp"
        mv yarn.lock.temp yarn.lock

        echo "Registry URLs updated while preserving @toptal and @topkit package sources"

    - name: Capture yarn.lock file checksum
      id: yarn-lock-checksum
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        echo "checksum=$(cksum yarn.lock)" >> $GITHUB_OUTPUT

    - name: yarn install
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        NPM_TOKEN: ${{ inputs.npm-token || env.NPM_TOKEN }}
        MAX_ATTEMPTS: ${{ inputs.max-attempts }}
      run: |
        for i in {1..$MAX_ATTEMPTS}; do
          printf "Trying to install #%s...\n" "$i"
          yarn install --non-interactive && break
          sleep 10 # 10s wait time
        done

      # We are manually checking for the changes in yarn.lock file, because
      # the `--frozen-lockfile` flag is not working correctly in workspaces with yarn v1
      # we can remove this step when we upgrade yarn or migrate to other package manager
    - name: Verify yarn.lock is unchanged
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        [ "${{ steps.yarn-lock-checksum.outputs.checksum }}" = "$(cksum yarn.lock)" ] || (echo 'yarn.lock changed after yarn install. Please make sure to commit yarn.lock changes.' && exit 1)

      # Undo any modifications to yarn.lock we might have done to leave
      # repo in the same state as it was before running yarn-install action
    - name: Restore original yarn.lock
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        if [ -f yarn.lock.original ]; then
          cp yarn.lock.original yarn.lock
          rm yarn.lock.original
        fi

    - name: Restore original .npmrc
      working-directory: ${{ inputs.path }}
      run: |
        if [ -f .npmrc.original ]; then
          cp .npmrc.original .npmrc
          rm .npmrc.original
        fi
      shell: bash
