name: Install dependencies
description: Install and cache node modules with yarn
inputs:
  npm-token:
    description: Access token type **Read-only**. Required for repository with private dependencies. If undefined, `env.NPM_TOKEN` is used
    required: false
  cache-version:
    description: "Cache version"
    default: "0.0"
    required: false
  path:
    description: Relative path under $GITHUB_WORKSPACE where to run `yarn install` command
    default: .
    required: false
  checkout-token:
    description: Repository checkout access token `GITHUB_TOKEN`. Required for self-hosted runners
    required: false
  npm-gar-token:
    description: Repository npm Artifact Registry access token `NPM_GAR_TOKEN`. Required when using self-hosted runners with npm in GAR (Google Artifact Registry, the npm registry works as a proxy-cache, downloading and storing the public npm packages)
    required: false
  max-attempts:
    description: How many times to retry installing. This is specially useful if the building of packages might fail because of network connections
    default: "1"
    required: false
outputs:
  cache-hit:
    description: "Indicates an exact match was found for `node_modules` || boolean"
    value: ${{ steps.node-modules-cache.outputs.cache-hit || steps.node-modules-cache-custom.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Set node version
      id: set-node-version
      run: echo version=$(node -v) >> $GITHUB_OUTPUT
      shell: bash

    - name: Get yarn cache
      id: yarn-cache
      run: echo dir=$(yarn cache dir) >> $GITHUB_OUTPUT
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token || env.NPM_TOKEN }}

    # This step is needed only because we want to update the cache when a new workspace
    # package has been added and we want symlinks to be presented in ./node_modules folder
    - name: Generate workspaces info
      working-directory: ${{ inputs.path }}
      run: |
        if grep -q "\"workspaces\":" package.json; then
          yarn --no-default-rc workspaces --json info > tmp-workspaces.json
        fi
      shell: bash

    - name: Checkout `cache action` from actions repository
      if: "inputs.checkout-token && contains(runner.name, 'inf-gha-runners-ci')"
      uses: actions/checkout@v3
      with:
        repository: toptal/actions
        token: ${{ inputs.checkout-token }}
        path: ./.github/cache_action/

    - name: Cache yarn and node_modules folder
      if: "inputs.checkout-token && contains(runner.name, 'inf-gha-runners-ci')"
      uses: ./.github/cache_action/cache/
      id: node-modules-cache-custom
      with:
        # Do not change the order of the values because if something goes wrong with the network or node_modules during
        # the caching process, GitHub can still end up creating a valid cache entry.
        # The cache from yarn is smaller and of higher priority for us
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles('**/yarn.lock', 'tmp-workspaces.json') }}-${{ inputs.cache-version }}

    - name: Cache yarn and node_modules folder
      if: "!contains(runner.name, 'inf-gha-runners-ci') || !inputs.checkout-token"
      uses: actions/cache@v3
      id: node-modules-cache
      with:
        # Do not change the order of the values because if something goes wrong with the network or node_modules during
        # the caching process, GitHub can still end up creating a valid cache entry.
        # The cache from yarn is smaller and of higher priority for us
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          **/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles('**/yarn.lock', 'tmp-workspaces.json') }}-${{ inputs.cache-version }}

    - name: Delete temporary tmp-workspaces.json
      shell: bash
      run: |
        [ -e tmp-workspaces.json ] && rm tmp-workspaces.json || echo "OK"

    # This step creates .npmrc file that references to npm registry in GAR (Google Artifact Registry)
    # The npm registry works as a proxy-cache, downloading and storing the public npm packages
    - name: Create .npmrc file using npm Artifact Registry
      if: "inputs.checkout-token && inputs.npm-gar-token && contains(runner.name, 'inf-gha-runners-ci')"
      run: |
        echo "registry=https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/" > ${{ inputs.path }}/.npmrc &&
        echo "//us-central1-npm.pkg.dev/toptal-ci/npm-registry/:username=_json_key_base64" >> ${{ inputs.path }}/.npmrc &&
        echo "//us-central1-npm.pkg.dev/toptal-ci/npm-registry/:_password=${{ inputs.npm-gar-token }}" >> ${{ inputs.path }}/.npmrc &&

        echo "@toptal:registry=https://registry.npmjs.org/" >> ${{ inputs.path }}/.npmrc &&
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token || env.NPM_TOKEN }}" >> ${{ inputs.path }}/.npmrc &&

        echo "@topkit:registry=https://registry.npmjs.org/" >> ${{ inputs.path }}/.npmrc &&
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token || env.NPM_TOKEN }}" >> ${{ inputs.path }}/.npmrc &&
        echo "always-auth=true" >> ${{ inputs.path }}/.npmrc
      shell: bash

    # This step changes the public npm registry in yarn.lock file to npm in AR
    # We still use the public npm registry to our private packages
    - name: Change registry in yarn.lock file to npm Artifact Registry
      if: "inputs.checkout-token && inputs.npm-gar-token && contains(runner.name, 'inf-gha-runners-ci')"
      run: |
        sed -i -e "s#https://registry.yarnpkg.com/#https://us-central1-npm.pkg.dev./toptal-ci/npm-registry/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://registry.npmjs.org/#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/@toptal/#https://registry.npmjs.org/@toptal/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/@topkit/#https://registry.npmjs.org/@topkit/#g" ${{ inputs.path }}/yarn.lock
      shell: bash

    - name: yarn install
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        NPM_TOKEN: ${{ inputs.npm-token || env.NPM_TOKEN }}
        MAX_ATTEMPTS: ${{ inputs.max-attempts }}
      run: |
        for i in {1..$MAX_ATTEMPTS}; do
          printf "Trying to install #%s...\n" "$i"
          yarn install --frozen-lockfile --non-interactive && break
          sleep 10 # 10s wait time
        done
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Revert changes in yarn.lock file
      if: "inputs.checkout-token && inputs.npm-gar-token && contains(runner.name, 'inf-gha-runners-ci')"
      run: |
        sed -i -e "s#https://us-central1-npm.pkg.dev./toptal-ci/npm-registry/#https://registry.yarnpkg.com/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/#https://registry.npmjs.org/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://registry.npmjs.org/@toptal/#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/@toptal/#g" ${{ inputs.path }}/yarn.lock
        sed -i -e "s#https://registry.npmjs.org/@topkit/#https://us-central1-npm.pkg.dev/toptal-ci/npm-registry/@topkit/#g" ${{ inputs.path }}/yarn.lock
      shell: bash

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3