name: Build & Push Docker Image
description: |
  Builds release image of a project and pushes to cloud
  ****
  envInputs:
    GITHUB_TOKEN: GitHub token. Is used to checkout `davinci` branch
    GCR_ACCOUNT_KEY: Necessary token to push image to Google cloud

inputs:
  sha:
    required: true
    description: 'Commit hash that will be used as a tag for the Docker image'
  image-name:
    required: true
    description: 'Name of the Docker image. Might be used in the next steps (for ex.: deploy a Docker image)'
  environment:
    required: false
    default: staging
    description: 'Determines additional procedures while creating a Docker image. || enum<<br/>`temploy`,<br/>`staging`,<br/>`production`,<br/>>'
  build-args:
    required: true
    description: 'Multiline string to describe build arguments that will be used during dockerization'
  docker-file:
    description: 'pathname to Docker file, by default [this dockerfile](https://github.com/toptal/davinci/blob/master/packages/ci/src/configs/docker/Dockerfile) is used'
    required: false
    default: ./davinci/packages/ci/src/configs/docker/Dockerfile

runs:
  using: composite
  steps:
    - name: Checkout davinci
      uses: actions/checkout@v2
      with:
        repository: toptal/davinci
        token: ${{ env.GITHUB_TOKEN }}
        path: davinci

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14.17'

    - id: meta-latest
      shell: bash
      run: |
        latest=$(if [ ${{ inputs.environment }} == 'temploy' ]; then echo false; else echo true; fi)
        echo "::set-output name=latest::$latest"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: gcr.io/toptal-hub/${{ inputs.image-name }}
        tags: |
          type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ inputs.sha }}
        flavor: |
          latest=${{ steps.meta-latest.outputs.latest }}

    - name: Login to GCloud Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ env.GCR_ACCOUNT_KEY }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push release image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        context: .
        file: ${{ inputs.docker-file }}
        build-args: ${{ inputs.build-args }}
