name: Get user slack from email
description: |
  Get user slack handler based on user email
  ****
  envInputs:
    SLACK_BOT_TOKEN: Slack bot token with scope "users:read.email" **Read-only**.
inputs:
  email:
    required: true
    description: User email
  slack-bot-token:
    required: true
    description: Slack bot token with scope "users:read.email" **Read-only**. If undefined, `env.SLACK_BOT_TOKEN` is used

outputs:
  slack-userId:
    description: "Slack user id"
    value: ${{ steps.slack-user.outputs.slackId }}

runs:
  using: composite
  steps:
    - name: Get slack user name
      id: slack-user
      shell: bash
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token || env.SLACK_BOT_TOKEN }}
      run: |
        data=$(curl -X POST https://slack.com/api/users.lookupByEmail \
          -H "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d 'email=${{ inputs.email }}')
        echo $data
        slackId=$(echo $data | jq -r '.user.id')
        echo "slackId=$slackId" >> $GITHUB_OUTPUT
