name: PR Checks

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  readme-existence:
    name: 'README.md file existence check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check README.md file existence
        run: |
          for f in [^node_modules]*/ ; do
            if [[ ! -f "$f/README.md" ]]
            then
                echo "README.md file does not exist in path: $f/README.md"
                exit 1
                break
            fi
          done

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'changeset-release/master' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - uses: ./yarn-install

      - uses: ./unit-tests

  trufflehog-scan:
    name: Trufflehog Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@v0.9l-beta
