name: Test Jira Deployments

on:
  workflow_dispatch:
  push:
    branches:
      - fx-3909-add-jira-deployments

jobs:
  release:
    name: Trigger Jira Deployments
    runs-on: ubuntu-latest
    env:
      DEVBOT_TOKEN: ${{ secrets.TOPTAL_DEVBOT_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Get new tag version
        id: tag-version
        run: |
          echo LATEST_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_OUTPUT

      - uses: toptal/davinci-github-actions/create-jira-deployment@v6.3.0
        name: Create Production Jira deployment
        with:
          token: ${{ env.DEVBOT_TOKEN }}
          environment: production
          environment-url: https://github.com/toptal/davinci-github-actions/releases/tag/${{ steps.tag-version.outputs.LATEST_TAG }}

      - uses: toptal/davinci-github-actions/create-jira-deployment@v6.3.0
        name: Create Alpha Jira deployment
        with:
          token: ${{ env.DEVBOT_TOKEN }}
          environment: alpha-package
          environment-url: https://github.com/toptal/davinci-github-actions/releases/tag/${{ steps.tag-version.outputs.LATEST_TAG }}
