name: 'Reuse Composite Action Workflow'

on:
  push:
    branches:
      - FX-NULL-test-parameter

jobs:
  reuse-action-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      pull-requests: write
      issues: write
    steps:
      - name: GSM Secrets
        id: secrets_manager
        uses: toptal/davinci-github-actions/gsm-secrets@master
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SA_IDENTITY_POOL }}
          secrets_name: |-
            TOPTAL_DEVBOT_TOKEN:toptal-ci/TOPTAL_DEVBOT_TOKEN

      - name: Parse secrets
        id: parse_secrets
        uses: toptal/davinci-github-actions/expose-json-outputs@master
        with:
          json: ${{ steps.secrets_manager.outputs.secrets }}

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: FX-NULL-test-parameter

      - name: Reuse my composite action
        uses: ./.github/actions/test-action
        with:
          github-token: ${{ steps.parse_secrets.outputs.TOPTAL_DEVBOT_TOKEN }}
          pr-number-text: '349'
          pr-number-integer: 943
